language: csharp
mono:
  - beta
solution: SolutionPub.sln
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade -r coreclr
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - npm install -g typescript
script:
  - cd src/SP.WEB && bower install && npm install && gulp deploy && gulp run-jtests
  - cd ../../tests/SP.WEB.Tests && dnu restore && dnx run-csharp-web-tests -parallel none
  - cd ../SP.BLL.Tests && dnu restore && dnx run-csharp-bll-tests -parallel none
