language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - npm install -g typescript
  - npm install -g karma-cli
  - bower install
  - npm install tsd
  - gulp wiredep-app
  - gulp run-jtests