language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - npm install -g typescript
  - cd $TEST_DIR && bower install && npm install && gulp wiredep-app && gulp run-jtests
  env:
  - TEST_DIR=src\SP