language: csharp
solution: SolutionPub.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - npm install -g typescript
script: cd src/SP && bower install && npm install && gulp deploy && gulp run-jtests
after_script:
  - nunit-console Tests/bin/Release/Tests.dll